### ISSUE TITLE
Reduce solid line brightness

### ISSUE THREAD

**Issue by supermitch** [UstymUkhman/matrix-theme#3]
A personal preference request: The solid lines, particularly the vertical ruler lines, are very bright, and I would prefer if they didn't jump out so much. Here's a screen shot showing what I mean:

<img width="438" alt="image" src="https://github.com/UstymUkhman/matrix-theme/assets/1152280/121253e0-cabd-4ade-a446-052cd041272c">

**Comment by UstymUkhman** [comment]
Hi @supermitch! Thanks for your feedback, I agree: will add some transparency to these lines if possible as soon as I find some time to come back to this project. In the meantime, feel free to star this theme if you like it to keep me motivated work in it further. Thanks!

**Comment by UstymUkhman** [comment]
Fixed in version `0.1.3`.
